version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update -y && apt-get install unzip
      - wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
      - unzip terraform_0.12.6_linx_amd64.zip
      - mv terraform /usr/bin/
  build:
    commands:
      - terraform apply -auto-approve terraform/application/
