version: 0.2

env:
  variables:
    RUBY_VERSION: "2.6"

phases:
  install:
    runtime-versions:
      ruby: "$RUBY_VERSION"
    commands:
      - gem install rails
      - bundle update --group test
      - apt-get update -y && apt-get install unzip
  pre_build:
    commands:
      - eval "$(aws ecr get-login --no-include-email)"
  build:
    commands:
      - bin/spring stop
      - rails test
      - export IMAGE_BASE="airport-hangout-frontend"
      - export IMAGE_TAG="$(cat VERSION.txt).$(date -u +%Y%m%d%H%M%S)"
      - export IMAGE_NAME="$IMAGE_BASE:$IMAGE_TAG"
      - docker build -t $IMAGE_NAME .
  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = '0' ]; then exit 1; fi
      - export ECR_URI=$(aws ecr describe-repositories --repository-names 'airport_hangout_ecr_repo' --query 'repositories[0].repositoryUri' --output=text)
      - export TAGGED_URI="$ECR_URI"":""$IMAGE_TAG"
      - export TAGGED_URI_LATEST="$ECR_URI"":latest"
      - docker tag $IMAGE_NAME $TAGGED_URI
      - docker tag $IMAGE_NAME $TAGGED_URI_LATEST
      - docker push $TAGGED_URI
      - docker push $TAGGED_URI_LATEST
      - printf '[{"name":"frontend", "imageUri":"%s"}]' $TAGGED_URI > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
