version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update -y && apt-get install unzip
      - cd tmp
      - wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
      - unzip -o terraform_0.12.6_linux_amd64.zip
      - mv terraform /usr/bin/
      - cd ..
  build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = '0' ]; then exit 1; fi
      - terraform init terraform/application/
      - terraform apply -auto-approve terraform/application/
