version: 0.2

env:
  variables:
    RUBY_VERSION: "2.6"

phases:
  install:
    runtime-versions:
      ruby: "$RUBY_VERSION"
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - gem install rails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - bin/spring stop && rails test
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
