version: 0.2

env:
  variables:
    RUBY_VERSION: "2.6"

phases:
  install:
    runtime-versions:
      ruby: "$RUBY_VERSION"
    commands:
      - apt-get update -y
      - gem install rails
      - bundle update --group test
  build:
    commands:
      - echo Build started on `date`
      - bin/spring stop && rails test
